//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FreeTrail
    {
        public int SeqID { get; set; }
        public string Name { get; set; }
        public string SchoolName { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string LocalPhone { get; set; }
        public string Course { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
    }
}
